### PR TITLE
PR: Use Spyder kernel spec to create kernel notebooks

### LINKED ISSUE #8: Make the notebook server to start Spyder kernels
This is the only way to connect a notebook to the Variable Explorer.

### PR DESCRIPTION
**Pull request by ccordoba12**
Fixes #8.

### CODE REVIEW

**Comment by ccordoba12** [comment]
@dalthviz, please verify that this is working on Windows for you. All you have to do is checkout my PR, start Spyder and finally run

    runfile

in a cell and verify that you get the result

    <function sitecustomize.runfile>

**Comment by dalthviz** [comment]
@ccordoba12 an error raises:

imagen

**Comment by ccordoba12** [comment]
Do you have the latest changes in Spyder 3.x branch?

**Comment by dalthviz** [comment]
Yep, the problem was in my conda installation, the changes did work after I reinstalled 👍 

imagen

**Comment by ccordoba12** [comment]
Great!

**Pull request merged**
