### PR TITLE
PR: Simplify plugin title

### PR DESCRIPTION
**Pull request by ccordoba12**
The plugin will be called *Jupyter Notebook* from now. Before we were adding the current file title to its name.

### CODE REVIEW

**Comment by goanpeca** [comment]
@ccordoba12 is this plugin going to be open as part of the files in the editor, or as a separate dock?

**Comment by ccordoba12** [comment]
It's a separate dock, docked next to the Editor.

**Comment by goanpeca** [comment]
The demo you did some time ago, it was also as part of the editor, no ?

**Comment by ccordoba12** [comment]
> The demo you did some time ago, it was also as part of the editor, no ?

Nop, it's always been a different plugin.

> UX wise having a separate thing for the notebooks is going to be ugly....

Sure, but:

1. It would be impossible to develop this as a separate project if we try to join it with the Editor.
2. It would put a lot of (additional) stress on the really complicated Editor code.

**Comment by goanpeca** [comment]
Well, we can think about that when this is more fleshed out anyway ;-)

**Comment by ccordoba12** [comment]
Yep, for now we want a working thing.

What we could do is to provide an API in Spyder 4 to extend the *Save*, *Save As*, etc, actions in our menus and main toolbar.

**Comment by goanpeca** [comment]
>what we could do is to provide an API in Spyder 4 to extend the Save, Save As, etc, actions in our menus and main toolbar.

:+1:

**Pull request merged**
