### PR TITLE
PR: Add menuBar with the actions available to each tab

### LINKED ISSUE #88: Show icons of Options menu actions above tabs
@dalthviz, I'd like to see if we can have something like JupyterLab

seleccion_001

At least our actions New, Open, Save as, and Open console should be above every tab.

I think it would be more intuitive for our users to see those actions easily accessible to not try to use the main ones. Also, I don't think people would be inclined to look for them in our Options menu.

### PR DESCRIPTION
**Pull request by dalthviz**
Fixes #88

### CODE REVIEW

**Comment by goanpeca** [comment]
@dalthviz screenshots please :-)

**Comment by dalthviz** [comment]
Preview:

imagen

**Comment by ccordoba12** [comment]
Please post the icons at the top of each tab and not at the bottom. Also, please don't the *Open recent* action and remove the **+** button from tabs right corner.

**Comment by dalthviz** [comment]
Preview:

imagen

**Comment by goanpeca** [comment]
That looks very weird @ccordoba12 :-\

**Comment by ccordoba12** [comment]
Should we post those icons next to the notebook tabs then?

**Comment by ccordoba12** [comment]
I just want to give people a way to understand that they need to use those icons instead of the regular ones, at least for now.

**Comment by ccordoba12** [comment]
So what do you propose? Leave things as they are?

I mean, if people try to use the open dialog from Spyder's regular toolbar, they will find that their notebooks are open in the Editor, not in the notebook pane.

I mention this because it happened to a person I was helping to install the notebook during SciPy.

**Comment by jitseniesen** [comment]
> Icons plus a menu bar plus more icons.... that is just too much :-\

I agree with @goanpeca here. I don't mind too much as a short-term fix for putting a release of the plugin out, but for the medium term I don't think it is a good idea to have to have two New buttons, two Open buttons, etc.

> I mean, if people try to use the open dialog from Spyder's regular toolbar, they will find that their notebooks are open in the Editor, not in the notebook pane.

It should be possible to have the Open button from Spyder's toolbar open notebooks in the Notebook pane and other files in the Editor pane; is there a problem with that? If there is a use case for opening notebooks in the Editor pane, then we may add a button to the Open dialog box to allow this.

**Comment by ccordoba12** [comment]
> I agree with @goanpeca here. I don't mind too much as a short-term fix for putting a release of the plugin out

Ok, I agree with both of you then. Sorry @dalthviz to make you waste your time :-/

> It should be possible to have the Open button from Spyder's toolbar open notebooks in the Notebook pane and other files in the Editor pane; is there a problem with that?

Not exactly. Right now that requires changes to Spyder itself, while it'd be better for this plugin to register a handler with the Spyder Open action. We should go with the first approach in Spyder 3, but we'd like to implement the second one in Spyder 4.

**Pull request closed without merging**
