### PR TITLE
PR: Implement dark theme

### PR DESCRIPTION
**Pull request by jitseniesen**
This PR renders notebooks using the JupyerLab dark theme if the Spyder interface is set to dark.

Screenshot_20200622_180737

It was not such a big change in the end but I learned a lot about JupyterLab, TypeScript and webpack in the process. You will see that the colour scheme of the JupyterLab dark theme is a bit different from Spyder: the text of the notebook pane is whiter and the background is blacker than in the other panes.

### CODE REVIEW

**Comment by ccordoba12** [comment]
@jitseniesen, it looks pretty awesome! Keep up with the good work here.

**Comment by kingwatam** [comment]
For some reason, spyder-notebook remains to have a white background even when Spyder is set to dark. I installed the latest spyder-notebook from conda.

**Comment by jitseniesen** [comment]
@kingwatam Can you please check the version of spyder-notebook that is reported in `Help > Dependencies`? The latest version is 0.3.1. One possible explanation is that Spyder is not using the new version; perhaps it got installed in the wrong environment.

**Comment by kingwatam** [comment]
I couldn't find spyder-notebook under dependencies, even though I have the notebook tab in Spyder. However, I could find spyder-notebook in Anaconda Navigator, version 0.2.3. That must be why. 

After uninstalling Spyder (4.0.1), and reinstalling it (4.1.5), as well as reinstalling spyder-notebook (0.3.1), it now works as expected.

**Pull request merged**
