### PR TITLE
PR: Update plugin to Spyder 6

### LINKED ISSUE #278: Use Spyder's dev branch in CI
Instead of installing Conda's Spyder package, clone Spyder from GitHub. Also update the contributing instructions with how to do this.

### PR DESCRIPTION
**Pull request by jitseniesen**
This was quite simple, the main change is to adapt to the Switcher plugin.

Fixes #278.

### CODE REVIEW

**Comment by ccordoba12** [comment]
The idea with the new Switcher plugin is that other plugins can depend on it in the same way that they depend on the MainMenu or Toolbar plugins.

So, you need to add the Switcer to the OPTIONAL list of plugins and declare methods decorated with on_plugin_available and on_plugin_teardown for it

**Comment by jitseniesen** [comment]
Thanks. I have this information in my brain somewhere, but it did not come out when I wrote the PR. Oops!

**Comment by ccordoba12** [comment]
No problem. I figured you missed that one because the new Switcher plugin has the same API as the old Switcher widget. Plus, we left a reference to `self.main.switcher` to run our tests more easily.

**Review by ccordoba12 — APPROVED** [review]
Looks good to me now, thanks @jitseniesen!

**Pull request merged**
