### PR TITLE
PR: Update server to Jupyterlab v2.2.7

### LINKED ISSUE #319: Increase legibility of the notebook dark theme
## Description of the problem

I like the dark theme for the notebook but think that the text and operators color could be a little brighter to increase their visibility (or maybe the background should be different?):

## Versions and main components

* Spyder Version:  4.1.5
* Python Version: 3.7.3
* Qt Version: 5.9.7
* PyQt Version: 5.9.2 (pyqt5-sip=12.8.0)
* Operating system: Windows

### jupyter:
```
# Name                    Version                   Build  Channel
jupyter                   1.0.0                    py37_7
jupyter_client            6.1.6                      py_0
jupyter_console           6.2.0                      py_0
jupyter_core              4.6.3                    py37_0
jupyterlab                2.2.6                      py_0
jupyterlab_pygments       0.1.1                      py_0
jupyterlab_server         1.2.0                      py_0
notebook                  6.1.1                    py37_0
spyder-notebook           0.3.0                      py_0    spyder-ide
```

## Dependencies

```
# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.6.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  6.0.6 (OK)
numpydoc >=0.6.0               :  0.9.1 (OK)
paramiko >=2.4.0               :  2.7.2 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.6.3 (OK)
pygments >=2.0                 :  2.7.1 (OK)
pylint >=1.0                   :  2.6.0 (OK)
pyls >=0.34.0;<1.0.0           :  0.35.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.7 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.2.1 (OK)
spyder_kernels >=1.9.4;<1.10.0 :  1.9.4 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.2 (OK)

# Optional:
cython >=0.21                  :  0.29.12 (OK)
matplotlib >=2.0.0             :  3.1.0 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  0.25.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  None (OK)

# Spyder plugins:
spyder_notebook                :  0.3.0 (OK)
```

### LINKED ISSUE #330: Upgrade Jupyter Lab to version 3
Incorporate all changes to the Notebook example in Jupyter Lab version 2 in here where relevant.

This is also the proper fix for #319.

### PR DESCRIPTION
**Pull request by jitseniesen**
Incorporate all changes from the `example-notebook` server in Jupyterlab up to version 2.2.7. The new version of theme-dark-extension fixes #319, which here was fixed by PR #331, so we can revert the changes made in that PR.

Fixes #330.

### CODE REVIEW

**Comment by jitseniesen** [comment]
This PR inadvertently removes the notebook toolbar, which may cause the failing test. In any case, I need to bring the toolbar back before merging, so I am converting the PR to draft.

**Comment by jitseniesen** [comment]
The notebook toolbar is not displayed when using the conda defaults channel, but it is displayed when using the conda-forge channel. If I connect Firefox to the Spyder notebook server, then the toolbar is also displayed. One difference between conda defaults and conda-forge is that the version of qt in conda defaults is 5.9.7 and in conda-forge it is 5.12.9. Since the qt library renders the web page, my working assumption is that there is a bug in qt 5.9.7 which makes the toolbar invisible in this PR and that this bug is fixed in qt 5.12.9. So I am parking this PR and hopefully conda defaults will get the new qt version at some point and everything will be fine then.

**Comment by ccordoba12** [comment]
I also think Qt 5.9 ships with a very old Chromium version, which is the cause of this error. Too bad, and eve worse is that Anaconda is taking too much time to update packages lately.

**Comment by jitseniesen** [comment]
Superseded by #396.

**Pull request closed without merging**
