### PR TITLE
 PR: Compatibility fixes for Spyder 6.0.0 beta 1

### PR DESCRIPTION
**Pull request by jitseniesen**
Two commits due to changes in Spyder API, change required version, and changes to make the tests run.

### CODE REVIEW

**Comment by glaubitz** [comment]
I just gave this a try on top of the current 0.5.0 release and it still has one failure:

```
[   25s] test_new_notebook failed (1 runs remaining out of 3).
[   25s]        <class 'TypeError'>
[   25s]        PluginMainWidget.add_corner_widget() missing 1 required positional argument: 'widget'
[   25s]        [<TracebackEntry /usr/lib/python3.11/site-packages/_pytest/runner.py:341>, <TracebackEntry /usr/lib/python3.11/site-packages/flaky/flaky_pytest_plugin.py:146>, <TracebackEntry /usr/lib/python3.11/site-packages/pluggy/_hooks.py:493>, <TracebackEntry /usr/lib/python3.11/site-packages/pluggy/_manager.py:115>, <TracebackEntry /usr/lib/python3.11/site-packages/pluggy/_callers.py:152>, <TracebackEntry /usr/lib/python3.11/site-packages/pluggy/_result.py:114>, <TracebackEntry /usr/lib/python3.11/site-packages/pluggy/_callers.py:137>, <TracebackEntry /usr/lib/python3.11/site-packages/pytestqt/plugin.py:180>, <TracebackEntry /usr/lib/python3.11/site-packages/pluggy/_callers.py:77>, <TracebackEntry /usr/lib/python3.11/site-packages/_pytest/runner.py:157>, <TracebackEntry /usr/lib/python3.11/site-packages/_pytest/runner.py:497>, <TracebackEntry /usr/lib/python3.11/site-packages/_pytest/runner.py:494>, <TracebackEntry /usr/lib/python3.11/site-packages/_pytest/python.py:1795>, <TracebackEntry /usr/lib/python3.11/site-packages/_pytest/fixtures.py:566>, <TracebackEntry /usr/lib/python3.11/site-packages/_pytest/fixtures.py:585>, <TracebackEntry /usr/lib/python3.11/site-packages/_pytest/fixtures.py:607>, <TracebackEntry /usr/lib/python3.11/site-packages/_pytest/fixtures.py:693>, <TracebackEntry /usr/lib/python3.11/site-packages/_pytest/fixtures.py:1069>, <TracebackEntry /usr/lib/python3.11/site-packages/pluggy/_hooks.py:493>, <TracebackEntry /usr/lib/python3.11/site-packages/pluggy/_manager.py:115>, <TracebackEntry /usr/lib/python3.11/site-packages/pluggy/_callers.py:152>, <TracebackEntry /usr/lib/python3.11/site-packages/pluggy/_result.py:114>, <TracebackEntry /usr/lib/python3.11/site-packages/pluggy/_callers.py:77>, <TracebackEntry /usr/lib/python3.11/site-packages/_pytest/fixtures.py:1123>, <TracebackEntry /usr/lib/python3.11/site-packages/_pytest/fixtures.py:895>, <TracebackEntry /home/abuild/rpmbuild/BUILD/spyder-notebook-0.5.1/spyder_notebook/widgets/tests/test_main_widget.py:67>, <TracebackEntry /home/abuild/rpmbuild/BUILDROOT/python-spyder-notebook-0.5.1-0.x86_64/usr/lib/python3.11/site-packages/spyder_notebook/widgets/main_widget.py:118>]
[   25s] test_new_notebook failed; it passed 0 out of the required 1 times.
```

Do you have any clue which patch I am missing to fix this? I'm trying to backport this PR to fix the package in openSUSE Tumblweed.

**Comment by jitseniesen** [comment]
@glaubitz I don't know. Commit [b223dd0](https://github.com/spyder-ide/spyder-notebook/pull/457/commits/b223dd027c976e4c5a6e7f13c93727d845769e7b) is the obvious candidate, but I don't see how it would give you that error message. What version of Spyder are you testing against?

**Comment by glaubitz** [comment]
> @glaubitz I don't know. Commit [b223dd0](https://github.com/spyder-ide/spyder-notebook/pull/457/commits/b223dd027c976e4c5a6e7f13c93727d845769e7b) is the obvious candidate, but I don't see how it would give you that error message. What version of Spyder are you testing against?

You're right, openSUSE is still on Spyder 5.5.4, so the testsuite failures I was hoping to fix with this PR are unrelated.

Sorry for the noise.

**Comment by jitseniesen** [comment]
I am merging this even though the CI tests do not pass so that I can continue work. I opened an issue so that I don't forget to fix the tests later.

**Pull request merged**
